#!/bin/bash
#
# Append information into encrypted files.
#

# Load functions
LIB="`dirname $0`/../../lib/keyringer/functions"
source $LIB || exit 1

# Get file
keyringer_get_file $2

OLDIFS=$IFS
IFS=$'\n'

CONTENT=($(keyringer_exec decrypt $BASEDIR $FILE))

echo " "
echo "$FILE currently has ${#CONTENT[@]} lines"
echo " "
echo "Now please write the content to be appended on $FILE, finnishing with Ctrl-D:"

APPEND=($(cat -))

NEW=( ${CONTENT[@]} ${APPEND[@]} )

for element in $(seq 0 $((${#NEW[@]} - 1))); do
  echo ${NEW[$element]}
done | keyringer_exec encrypt $BASEDIR $FILE

IFS="$OLDIFS"
