#!/bin/bash
#
# Append information into encrypted files.
#

# Load functions
LIB="`dirname $0`/../../lib/keyringer/functions"
source $LIB || exit 1

# Get file
keyringer_get_file $2

OLDIFS=$IFS
IFS=$'\n'

CONTENT=($(keyringer_exec decrypt $BASEDIR $FILE))

if [ "$1" = "append" ]; then
  # only display directions if we're running append, not append-batch
  echo " "
  echo "$FILE currently has ${#CONTENT[@]} lines"
  echo " "
  echo "Now please write the content to be appended on $FILE, finnishing with Ctrl-D:"
fi

APPEND=($(cat -))

NEW=( ${CONTENT[@]} ${APPEND[@]} )

for element in $(seq 0 $((${#NEW[@]} - 1))); do
  echo ${NEW[$element]}
done | keyringer_exec encrypt-batch $BASEDIR $FILE

IFS="$OLDIFS"
