#!/bin/bash
#
# Decrypt files.
#

# Load functions
LIB="`dirname $0`/../../lib/keyringer/functions"
source "$LIB" || exit 1

# Get file
keyringer_get_file "$2"

# Decrypt
gpg --quiet --use-agent -d "$KEYDIR/$FILE"
