#!/bin/bash
#
# Remove files.
#

# Load functions
LIB="`dirname $0`/../../lib/keyringer/functions"
source $LIB
keyringer_set_env $*

# Get file
keyringer_get_file $2

# Remove
if [ -d "$KEYDIR/.git" ]; then
  ./git $KEYDIR rm $FILE --force
fi
