#!/bin/bash
#
# Remove files.
#

# Load functions
LIB="`dirname $0`/../../lib/keyringer/functions"
source $LIB

# Config
BASEDIR="$1"
FILE="`keyringer_filename $2`"
KEYDIR="$BASEDIR/keys"
BASENAME="`basename $0`"

# Setup
if [ -z "$FILE" ]; then
  echo "Usage: `basename $0` <basedir> <file>"
  exit 1
elif [ ! -f "$KEYDIR/$FILE" ]; then
  echo "File not found: $KEYDIR/$FILE"
  exit 1
fi

# Remove
if [ -d "$KEYDIR/.git" ]; then
  ./git $KEYDIR rm $FILE --force
fi
