#!/bin/bash
#
# Edit keys.
#

# Load functions
LIB="`dirname $0`/../../lib/keyringer/functions"
source "$LIB" || exit 1

# Get file
keyringer_get_file "$2"

# Set recipients file
keyringer_set_recipients "$FILE"

# Warn user
echo "Make sure that $BASEDIR is atop of an encrypted volume."

# Set a tmp file
keyringer_set_tmpfile edit

# Decrypt the information to the file
$GPG --yes -o "$TMPWORK" --use-agent -d "$KEYDIR/$FILE"

if [ "$BASENAME" == "edit" ]; then
  APP="$EDITOR"
elif [ "$BASENAME" == "open" ]; then
  if which xdg-open &> /dev/null; then
    APP="xdg-open"
  else
    echo "You should have xdg-open application to perform this action, aborting."
    exit 1
  fi
fi

# Prompt
echo "Press any key to open the decrypted data with $APP, Ctrl-C to abort"
read key
$APP "$TMPWORK"

# Encrypt again
$GPG --yes -o "$KEYDIR/$FILE" --use-agent --armor -e -s $(keyringer_recipients "$RECIPIENTS_FILE") "$TMPWORK"

# Remove temp file
keyringer_unset_tmpfile "$TMPWORK"
