#!/bin/bash
#
# Edit keys.
#

# Load functions
LIB="`dirname $0`/../../lib/keyringer/functions"
source $LIB || exit 1
keyringer_set_env $*

# Get file
keyringer_get_file $2

# Warn user
echo "Make sure that $BASEDIR is atop of an encrypted volume."

# Set a tmp file
keyringer_set_tmpfile edit

# Decrypt the information to the file
gpg --yes -o $TMPWORK --use-agent -d $KEYDIR/$FILE

# Prompt
echo "Press any key to open the decrypted data into $EDITOR, Ctrl-C to abort"
read key
$EDITOR $TMPWORK

# Encrypt again
gpg --yes -o $KEYDIR/$FILE --use-agent --armor -e -s $(keyringer_recipients $RECIPIENTS) $TMPWORK

# Remove temp file
keyringer_unset_tmpfile $TMPWORK
