#!/bin/bash
#
# Git wrapper.
#

# Load functions
LIB="`dirname $0`/../../lib/keyringer/functions"
source $LIB
keyringer_set_env $*

# Aditional parameters
CWD="`pwd`"

if [ -z "$BASEDIR" ]; then
  echo "Usage: keyringer <keyringer> `basename $0` [arguments]"
  exit 1
fi

shift
mkdir -p $BASEDIR && cd $BASEDIR && git $*
cd $CWD
