#!/bin/bash
#
# Git wrapper.
#

BASEDIR="$1"
CWD="`pwd`"

if [ -z "$BASEDIR" ]; then
  echo "Usage: keyringer <keyringer> `basename $0` [arguments]"
  exit 1
fi

shift
mkdir -p $BASEDIR && cd $BASEDIR && git $*
cd $CWD
