#!/bin/bash
#
# List keys.
#

BASEDIR="$1"
KEYDIR="$BASEDIR/keys"
CWD="`pwd`"

if [ -z "$KEYDIR" ]; then
  echo "Usage: keyringer `basename $0` [arguments]"
  exit 1
fi

shift
cd $KEYDIR && ls $*
cd $CWD
