#!/bin/bash
#
# List keys.
#

# Load functions
LIB="`dirname $0`/../../lib/keyringer/functions"
source $LIB
keyringer_set_env $*

# Aditional parameters
CWD="`pwd`"

if [ -z "$KEYDIR" ]; then
  echo "Usage: keyringer <keyring> `basename $0` [arguments]"
  exit 1
fi

shift
cd $KEYDIR && ls $*
cd $CWD
