#!/bin/bash
#
# Recipient management.
#

# Load functions
LIB="`dirname $0`/../../lib/keyringer"
source "$LIB/functions" || exit 1

# Command parser
keyringer_get_command "$2"

# Create options file if old repository
if [ ! -e "$OPTIONS" ]; then
  echo "Creating options file..."
  touch "$OPTIONS"
  keyringer_exec git "$BASEDIR" add config/options
fi

if [ "$COMMAND" == "ls" ]; then
  cat "$OPTIONS"
elif [ "$COMMAND" == "edit" ]; then
  "$EDITOR" "$OPTIONS"
elif [ "$COMMAND" == "add" ]; then
  shift 2
  echo $* >> "$OPTIONS"
else
  printf "%s: No such command %s\n"  "$BASENAME" "$COMMAND"
  exit 1
fi
