#!/bin/bash
#
# Recipient management.
#

# Load functions
LIB="`dirname $0`/../../lib/keyringer"
source $LIB/functions
keyringer_set_env $*

# Command parser
keyringer_get_command $2

# Create options file if old repository
if [ ! -e "$OPTIONS" ]; then
  echo "Creating options file..."
  touch $OPTIONS
  keyringer_exec git $BASEDIR add config/options
fi

if [ "$COMMAND" == "ls" ]; then
  cat $OPTIONS
elif [ "$COMMAND" == "edit" ]; then
  $EDITOR $OPTIONS
elif [ "$COMMAND" == "add" ]; then
  shift 2
  echo $* >> $OPTIONS 
else
  echo "$BASENAME: No such command $COMMAND"
  exit 1
fi
