#!/bin/bash
#
# Recipient management.
#

# Load functions
LIB="`dirname $0`/../../lib/keyringer"
source $LIB/functions
keyringer_set_env $*

# Command parser
keyringer_get_command $2

if [ "$COMMAND" == "ls" ]; then
  cat $RECIPIENTS
elif [ "$COMMAND" == "edit" ]; then
  $EDITOR $RECIPIENTS
else
  echo "$BASENAME: No such command $COMMAND"
  exit 1
fi
