#!/bin/bash
#
# Recipient management.
#

# Load functions
LIB="`dirname $0`/../../lib/keyringer"
source "$LIB/functions" || exit 1

# Command parser
keyringer_get_command "$2"

if [ "$COMMAND" == "ls" ]; then
  cat "$RECIPIENTS"
elif [ "$COMMAND" == "edit" ]; then
  "$EDITOR" "$RECIPIENTS"
else
  printf "%s: No such command %s\n" "$BASENAME" "$COMMAND"
  exit 1
fi
