#!/bin/bash
#
# Re-encrypt files to multiple recipients.
#

# Load functions
LIB="`dirname $0`/../../lib/keyringer/functions"
source "$LIB" || exit 1

function keyringer_recrypt {
  # Get file
  keyringer_get_file "$1"

  # Set recipients file
  keyringer_set_recipients "$FILE"

  # Set pipefail so we can detect decryption failures
  set -o pipefail

  # Recrypt
  $GPG --use-agent -d "$KEYDIR/$FILE" | \
  $GPG --use-agent --armor -e -s $(keyringer_recipients "$RECIPIENTS_FILE") > "$KEYDIR/$FILE"

  if [ "$?" != "0" ]; then
    exit 1
  fi
}

if [ ! -z "$2" ]; then
  keyringer_recrypt $2
else
  cd $KEYDIR && find | while read file; do
    if [ ! -d "$KEYDIR/$file" ]; then
      keyringer_recrypt "$file"
    fi
  done
fi
