Document: keyringer
Title: Debian keyringer Manual
Author: <insert document author here>
Abstract: This manual describes what keyringer is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/keyringer/keyringer.sgml.gz

Format: postscript
Files: /usr/share/doc/keyringer/keyringer.ps.gz

Format: text
Files: /usr/share/doc/keyringer/keyringer.text.gz

Format: HTML
Index: /usr/share/doc/keyringer/html/index.html
Files: /usr/share/doc/keyringer/html/*.html
