#!/bin/bash
#
# Decrypt files.
#

FILE="$1"
BASENAME="`basename $0`"

if [ -z "$FILE" ]; then
  echo "Usage: `basename $0` <file>"
  exit 1
elif [ ! -f "keys/$FILE" ]; then
  echo "File not found"
  exit 1
fi

gpg -d keys/$FILE
