#!/bin/bash
#
# Re-encrypt files to multiple recipients.
#

FILE="$1"
BASENAME="`basename $0`"
RECIPIENTS="config/recipients"

if [ -z "$FILE" ]; then
  echo "Usage: `basename $0` <file>"
  exit 1
elif [ ! -f "$RECIPIENTS" ]; then
  echo "No recipient config was found"
  exit 1
elif [ ! -f "keys/$FILE" ]; then
  echo "File not found"
  exit 1
fi

recipients="$(awk '{ print "-r " $2 }' $RECIPIENTS | xargs)"
gpg -d keys/$FILE | gpg --armor -e -s $recipients > keys/$FILE
