#!/usr/bin/env bash
#
# Remove files.
#

# Load functions
LIB="`dirname $0`/../functions"
source "$LIB" || exit 1

# Get file
keyringer_get_file "$2"

# Set options
if [ ! -z "$3" ]; then
  shift 2
  OPTS="$*"
fi

# Remove
if [ -d "$BASEDIR/.git" ]; then
  keyringer_exec git "$BASEDIR" rm $OPTS "keys/$FILE"
fi
