#!/bin/bash
#
# Git wrapper.
#

# Load functions
LIB="`dirname $0`/../functions"
source "$LIB" || exit 1

# Aditional parameters
CWD="`pwd`"

# Fix positional arguments
shift

# Run git command
mkdir -p "$BASEDIR" && cd "$BASEDIR" && git $*
cd "$CWD"
