#!/usr/bin/env bash
#
# List keys.
#

# Load functions
LIB="`dirname $0`/../functions"
source "$LIB" || exit 1

# Aditional parameters
CWD="`pwd`"

# Avoid leading slash
shift
ARGS="`echo "$*" | sed -e "s|^/*||"`"

# Run list command
cd "$KEYDIR/$RELATIVE_PATH" && ls $ARGS
cd "$CWD"
